export { default as Navbar } from './Navbar/Navbar'
export { default as HomePage } from './HomePage/HomePage'
export { default as ProductPage } from './ProductPage/ProductPage'
export { default as CartPage } from './CartPage/CartPage'
export { default as WishlistPage } from './WishlistPage/WishlistPage'
export { default as Footer } from './Footer/Footer'